playlists:
  - title: naat
    link: https://www.youtube.com/playlist?list=PL4rGrsY5H6X5G6h_wLXrG9Yk5-t1z9wWb
  - title: noko
    link: https://www.youtube.com/playlist?list=PL4rGrsY5H6X5bD_pb_3sL_UQKYVe8BdTI
