webdav_url: https://cloud.hamzarafi.com/remote.php/dav/files/hamza/Audio/Library
playlists:
  - title: naat
    link: https://www.youtube.com/playlist?list=PL4rGrsY5H6X5G6h_wLXrG9Yk5-t1z9wWb
  - title: noko
    link: https://www.youtube.com/playlist?list=PL4rGrsY5H6X5bD_pb_3sL_UQKYVe8BdTI
  - title: Arabic Poetry
    link: https://www.youtube.com/playlist?list=PL4rGrsY5H6X4QgvRo6j7M1br0hGndNJzy
  - title: pak sufi
    link: https://www.youtube.com/playlist?list=PL4rGrsY5H6X5xPg4UI_HATbKqdLSElVXt
  - title: turk
    link: https://www.youtube.com/playlist?list=PL4rGrsY5H6X4zfk4uu4cqeiyCNVIGVBzY
  - title: ant
    link: https://www.youtube.com/playlist?list=PL4rGrsY5H6X7oGrVJYPzmUSeAsxxLgwYo
  - title: Fr
    link: https://www.youtube.com/playlist?list=PL4rGrsY5H6X4qfH4ADd7wvpzsfnSrQ3Qd
  - title: أغاني العرب
    link: https://www.youtube.com/playlist?list=PL4rGrsY5H6X7-Wb2-IsDdFmgp5srO6sBg
  # - title:
  #   link:
